public with sharing class HelloGithubActions {
    public HelloGithubActions() {

    }

    public static void hello() {
        System.debug('Hello Github Actions World 234456789!!!');
        System.debug('finish feature1, and all develop work is done in feature 1 beanch');
        System.debug('add some additional change for feature1, and all develop work is done in feature 1 beanch');
    }
}


