
name: CI Process

on:
  push:
    branches: [ master ]
    paths:
            - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
            - 'force-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
   
     # Install Salesforce CLI
    - name: Install Salesforce CLI
      run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
        
     # Store secret for dev hub
    - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

     # Authenticate dev hub
    - name: 'Authenticate Dev Hub'
      run: 'sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
  
     # Create scratch org
    - name: 'Create scratch org'
      run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'
      
     # Deploy source to scratch org
    - name: 'Push source to scratch org'
      run: 'sfdx force:source:push'
 
    - name: Run Apex test
      run: 'sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20'
        
    - name: 'Delete scratch org'
      if: always()
      run: 'sfdx force:org:delete -p -u scratch-org'
